services:
  - type: web
    name: byggassistent
    env: python
    plan: free
    buildCommand: ./build.sh
    startCommand: python app.py
    envVars:
      - key: SPACY_MODEL_PATH
        value: "nb_core_news_sm"  # Eller lokal sti hvis du vet hvor modellen er
    regions:
      - oregon
